### ISSUE TITLE
List of tags and categories 

### ISSUE THREAD

**Issue by asarkar** [nicdun/astro-tech-blog#168]
I like the minimalist style, thanks for making the theme freely available. However, there’s one feature that I really want in my blog which isn’t present in the OOTB theme. It’s a list of tags, and optionally categories, ordered by popularity. Is this something you can add to the theme? If not, can a user of your user make this modification easily?

**Comment by nicdun** [comment]
can you provide some more information? You mean on the tag page itself, or a second sub page?

**Comment by asarkar** [comment]
I’m not seeing a “tag page” per se, where all the tags are listed. I only see posts that are tagged. You can see what I’m referring to on this page:  https://blogs.asarkar.com/tags/#gsc.tab=0

**Comment by nicdun** [comment]
Thanks for leaving an example - will implement this in the nearer future!

**Comment by nicdun** [comment]
Furthermore, find the tag page attached: https://astro-tech-blog-ten.vercel.app/tags

**Comment by asarkar** [comment]
I’ve two questions:
1. How does one get to the tags page easily?
2. Does clicking on a tag (either on the tags page or on a post) list all the articles that have that tag?

**Comment by nicdun** [comment]
1. will that improve also - actually only by adress manipulation
2. that's correct - click a tag and you will find all posts with that tag

**Comment by asarkar** [comment]
Thank you for the quick turnaround. There's one more problem that I noticed regarding the tags. On the home/landing page, clicking on a tag on a story card opens the story, not the posts associated with that tag. This is because the whole card is a link to the post, but the tags give the impression of being individually clickable because their appearances change on mouseover.

See this video

https://github.com/user-attachments/assets/e0e8526e-1f4b-40ed-b442-a0f895c0f4aa

**Comment by nicdun** [comment]
fixed with https://github.com/nicdun/astro-tech-blog/pull/222
